// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZcgHIQ9UQ2I78WwMehU6PP5zGJiQ7MQ0',
    appId: '1:649622728671:web:ce42bacc96224edddede6a',
    messagingSenderId: '649622728671',
    projectId: 'gona-d5e94',
    authDomain: 'gona-d5e94.firebaseapp.com',
    databaseURL: 'https://gona-d5e94-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'gona-d5e94.appspot.com',
    measurementId: 'G-SX1EPN0RVC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPT5InHcy8c65KCn9EYXNEKTnfbHgbGeE',
    appId: '1:649622728671:android:d570bdb681d60b6edede6a',
    messagingSenderId: '649622728671',
    projectId: 'gona-d5e94',
    databaseURL: 'https://gona-d5e94-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'gona-d5e94.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCg1mSbyKsuF3gwONtMUzZL-H6qzgMABDA',
    appId: '1:649622728671:ios:a35d33d7f08f8e10dede6a',
    messagingSenderId: '649622728671',
    projectId: 'gona-d5e94',
    databaseURL: 'https://gona-d5e94-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'gona-d5e94.appspot.com',
    androidClientId: '649622728671-e2phphvbe8n3ecihfscpqu7r3itif4de.apps.googleusercontent.com',
    iosClientId: '649622728671-g9qqp1av3djgp4snd7ug7bgvs15k3o8n.apps.googleusercontent.com',
    iosBundleId: 'com.example.gonaVendor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCg1mSbyKsuF3gwONtMUzZL-H6qzgMABDA',
    appId: '1:649622728671:ios:b18bd8e209fff988dede6a',
    messagingSenderId: '649622728671',
    projectId: 'gona-d5e94',
    databaseURL: 'https://gona-d5e94-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'gona-d5e94.appspot.com',
    androidClientId: '649622728671-e2phphvbe8n3ecihfscpqu7r3itif4de.apps.googleusercontent.com',
    iosClientId: '649622728671-2tgm4m5vqhkdf7l4urldf649pvndtvcv.apps.googleusercontent.com',
    iosBundleId: 'com.example.gonaVendor.RunnerTests',
  );
}
