// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZcgHIQ9UQ2I78WwMehU6PP5zGJiQ7MQ0',
    appId: '1:649622728671:web:ce42bacc96224edddede6a',
    messagingSenderId: '649622728671',
    projectId: 'gona-d5e94',
    authDomain: 'gona-d5e94.firebaseapp.com',
    storageBucket: 'gona-d5e94.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPT5InHcy8c65KCn9EYXNEKTnfbHgbGeE',
    appId: '1:649622728671:android:d45f8ea55c4bc18bdede6a',
    messagingSenderId: '649622728671',
    projectId: 'gona-d5e94',
    storageBucket: 'gona-d5e94.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCg1mSbyKsuF3gwONtMUzZL-H6qzgMABDA',
    appId: '1:649622728671:ios:92ab75bec5a34e2adede6a',
    messagingSenderId: '649622728671',
    projectId: 'gona-d5e94',
    storageBucket: 'gona-d5e94.appspot.com',
    androidClientId: '649622728671-e2phphvbe8n3ecihfscpqu7r3itif4de.apps.googleusercontent.com',
    iosClientId: '649622728671-n9bk5pc4gvl6tmjciuh64ialppfpdrbi.apps.googleusercontent.com',
    iosBundleId: 'com.example.gona',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCg1mSbyKsuF3gwONtMUzZL-H6qzgMABDA',
    appId: '1:649622728671:ios:009e062a02074c88dede6a',
    messagingSenderId: '649622728671',
    projectId: 'gona-d5e94',
    storageBucket: 'gona-d5e94.appspot.com',
    androidClientId: '649622728671-e2phphvbe8n3ecihfscpqu7r3itif4de.apps.googleusercontent.com',
    iosClientId: '649622728671-ji0tuvg847e8o58spns1r44s7stin9rn.apps.googleusercontent.com',
    iosBundleId: 'com.example.gona.RunnerTests',
  );
}
